### ISSUE TITLE
DFD Comments - Sept 17

### ISSUE THREAD

**Issue by germonprez** [so7itud3/ISQA-3420-850#4]
The DFD is looking good. I would like you to be more explicit on the data flows. For example, Browse Results Request should be more like Request for all Software Package and License Information (Same would hold true for the process). Be descriptive.

**Comment by so7itud3** [comment]
I've made some changes to the DFD and added the NIST portion to the DFD as well.

**Comment by germonprez** [comment]
Looks really good. Well done!
